POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3ROYW1lIiwiaWQiOiI1ZGY1OTJlMmEzNzJiMTgyOWNhYTcyOGMiLCJpYXQiOjE1NzYzNzUwODZ9.SplM-k-Kvq4YuUt0gRcIQOMHLFw9A8Xh5gN05qDdPX8

{
    "title": "Test Post with Token",
    "author": "Test Author",
    "url": "www.test-webpage.com",
    "likes": 5
}